[env:freenove_esp32_wrover]
platform = espressif32
board = freenove_esp32_wrover
framework = arduino
monitor_speed = 115200
lib_deps =
    me-no-dev/ESP Async WebServer @ ^1.2.3
    me-no-dev/AsyncTCP @ ^1.1.1